# Generated by Django 4.2.9 on 2024-02-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_category_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='messages',
            new_name='message',
        ),
    ]
